import requests
import argparse
import os
import sys

def main():
    parser = argparse.ArgumentParser(description="Fuzz a paramater (GET/POST) from a list of value from a file")
    parser.add_argument("url", metavar="URL", type=str, help="url where `FUZZ` is the parameter to fuzz")
    parser.add_argument("-f", "--file", dest="file", help="file where the fuzz pattern are stored", required=True)
    parser.add_argument("-b", "--badboy", dest="badboy", help="message generated by the webpage if the keyword is filtered", required=True)
    args = vars(parser.parse_args())
    try:
        f = open(args['file'], 'r')
    except Exception as e:
        print(e)
        sys.exit(1)
    lines = f.readlines()
    for line in lines:
        payload = args['url'].replace("FUZZ", line[0:len(line)-1])
        r = requests.get(payload)
        if args["badboy"] not in r.text:
            print("[passed] {}".format(line), end='')
        else:
            print("[filtered] {}".format(line), end='')

if __name__ == "__main__":
    main()
